sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t sunlee/color-app -f Dockerfile.dev .
script:
  - docker run -e CI=true sunlee/color-app npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "color-app"
  env: "ColorApp-env"
  bucket: "elasticbeanstalk-ap-southeast-2-730163571022"
  bucket_path: "color-app"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY